### ISSUE TITLE
Propose: update smebberson/alpine-base to 3.X.0 in agent-base

### ISSUE THREAD

**Issue by tunezaq** [dataloop/docker-alpine#1]
smebberson has a new image which supports alpine 3.4
https://hub.docker.com/r/smebberson/alpine-base/

https://alpinelinux.org/posts/Alpine-3.4.0-released.html

**Comment by tomashley** [comment]
agent-base has now been upgraded to 3.1.0

https://github.com/dataloop/docker-alpine/commit/d82265834d5fcbd362251d0cf425f8d5f2434328
