### ISSUE TITLE
Links in README.md broken

### ISSUE THREAD

**Issue by davidhiendl** [dataloop/docker-alpine#13]
The README.md file at https://github.com/outlyerapp/docker-alpine/blob/master/dataloop-docker/README.md has broken links referencing the old repo and the run commands reference the old docker image. The same applies to the Kubernetes and Docker Swarm example.

**Comment by tomashley** [comment]
Thanks for pointing this out. 

I have updated the readme to reflect the deprecation of `dataloop-docker` and the continued docker monitoring under the image `outlyer\agent`.
