### ISSUE TITLE
Docker Agent is reporting false network metrics

### ISSUE THREAD

**Issue by davidhiendl** [dataloop/docker-alpine#14]
The docker agent seems to be reporting false networking metrics. It appears to report on the containers internal interfaces and is completely unaware of the host interfaces (my hosts have several interfaces, but the agent reports only the 2 inside the container, eth0 which is Docker Overlay and eth1 which is the bridge).

While transferring several hundred mb/s on the host the agent still reporting only a few kb/s which probably are what the agent is reporting back to servers.

Operation System: Debian 8 / Jessie
Kernel from Backports: SMP Debian 4.9.18-1~bpo8+1 (2017-04-10)
Docker Version: 17.04.0-ce

**Comment by alexdias** [comment]
Thanks for submitting this issue.

The docker agent runs inside its own container, and thus will not report metrics for the underlying host.
Can I ask where in our UI were you expecting to see host metrics?

As a workaround, if you'd like to have a host agent on the UI (and thus have host metrics), you can run the agent on your actual hosts (instead of inside a docker container). You can pass a `--docker` flag when running the agent to make it monitor docker containers.

**Comment by davidhiendl** [comment]
I was talking with @tradel yesterday and from what I understand the agent, when deployed as a container, should be reporting the host metrics. I mean that's the reason why you are mounting /proc & /sys into the container. So when I add widgets to the dashboard or create a query based on that agent it should actually be reporting metrics about the host itself. At the moment it looks like it is reporting CPU and memory metrics for the host correctly but not network metrics.

Isn't the hole point of the docker agent container to **replace** the host-deployed agent? If I need it to monitor the host than what is the point in creating a docker agent anyway: You could just as easily have added the docker container monitoring to the agent deployed on the host.

**Comment by tradel** [comment]
Hi @DavidHiendl. We are discussing a fix for this and we have a few ideas. We will update you soon. Thanks.

**Comment by alexdias** [comment]
Hi @DavidHiendl,

Apologies for the delay on this. Could you run the docker agent with the `--net=host` flag? This should make the agent report host metrics correctly.

**Comment by davidhiendl** [comment]
@alexdias Docker Swarm mode does not allow services to be deployed with --net=host and/or privileged flags.

**Comment by gonzohunter** [comment]
Hi @DavidHiendl, this is a challenge faced by all monitoring solutions. We are stuck between the Swarm Mode trying to abstract away the underlying host, and our users who require monitoring of that host.

Some of our competitors have just given up in this area, but we are actively working to make it better. There have been several requests to support `--net=host` in Swarm mode, but so far Docker have not really given a response either way:
- https://github.com/moby/moby/issues/25873
- https://github.com/docker/swarmkit/issues/989

I understand their reasoning to try and keep the host hidden, but there are also valid use cases (like ours) where you need to break that rule. One option would be to install software requiring this on the host, but I can't imagine Docker want to push people down that route.

In the meantime we are working on a short-term fix–which may need to change in future, depending on where Docker goes–around the `net=host` requirement.

We will have a solution for this soon.

**Comment by alexdias** [comment]
@DavidHiendl I have a small function that will do what is required here. Could you please update your base.py plugin? On your main overview page (https://app.outlyer.com/YOUR_ORG/YOUR_ACCOUNT/#/setup/overview), on the left hand side, could you please click on "Setup Monitoring", then "Plugins List", and finally on base.py. On the code editor view, there should be a function called `check_netio`. Could you please replace it with:
```
def check_netio():
    sys_path = '/rootfs/sys'  # change this to the directory your host sys is mounted to
    net_class_path = os.path.join(sys_path, 'class', 'net')
    metric_keys = {
        'bytes_sent': 'tx_bytes',
        'bytes_recv': 'rx_bytes',
        'packets_sent': 'tx_packets',
        'packets_recv': 'rx_packets',
        'errin': 'rx_errors',
        'errout': 'tx_errors',
        'dropin': 'rx_dropped',
        'dropout': 'tx_dropped',
    }
    net_excludes = ['teredo', 'isatap', 'loopback']
    net_map = {}
    for our_key, sys_key in metric_keys.iteritems():
        current_sum = 0
        for interface in os.listdir(net_class_path):
            if interface in net_excludes:
                continue
            stats_folder = os.path.join(net_class_path, interface, 'statistics')
            metric_file = os.path.join(stats_folder, sys_key)
            try:
                with open(metric_file, 'r') as stat_file:
                    stat = stat_file.read()
                stat_value = int(stat)
                net_map['network.' + interface.replace(' ', '_').lower() + '.' + our_key] = stat_value
                current_sum += stat_value
            except Exception:
                continue
            
        net_map['network.' + our_key] = current_sum
    return net_map
```

After you've replaced it, you can run it against an agent to test it, and click "Save changes" so that future runs will use it.

Let me know how this works for you!

**Comment by davidhiendl** [comment]
Hello @alexdias , thanks for the update. This doesn't seem to be working at all. After replacing the function in question I don't seem to be getting ANY metrics for this plugin anymore. After restoring to the old version it seems to be working again.

**Comment by davidhiendl** [comment]
Closing. The issue was that the documentation only said to mount `/sys/fs:/rootfs/sys/fs` which is insufficient. The documentation has since been updated.
